// 离线缓存：页面联网时优先取最新版（3 秒没回应就先用缓存），像素图等静态文件直接用缓存
// ASSETS 列表由 scripts/sw-assets.mjs 在构建后自动填充
const CACHE = 'mir-muv6bxw4'
const ASSETS = [
  './',
  './index.html',
  './manifest.webmanifest',
  './favicon.svg',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './icons/icon-maskable-512.png',
  './icons/apple-touch-icon.png',
  "./sprites/hero/base.png",
  "./sprites/hero/body/armour_blue_gold.png",
  "./sprites/hero/body/chainmail.png",
  "./sprites/hero/body/dragonarm_brown.png",
  "./sprites/hero/body/dragonarm_cyan.png",
  "./sprites/hero/body/dragonarm_pearl.png",
  "./sprites/hero/body/dragonarm_red.png",
  "./sprites/hero/body/leather_armour.png",
  "./sprites/hero/body/plate.png",
  "./sprites/hero/body/plate_black.png",
  "./sprites/hero/body/ringmail.png",
  "./sprites/hero/body/robe_black_gold.png",
  "./sprites/hero/body/robe_blue.png",
  "./sprites/hero/body/robe_clouds.png",
  "./sprites/hero/body/robe_green_gold.png",
  "./sprites/hero/body/robe_purple.png",
  "./sprites/hero/body/robe_rainbow.png",
  "./sprites/hero/body/robe_red_gold.png",
  "./sprites/hero/body/robe_white.png",
  "./sprites/hero/body/robe_white_blue.png",
  "./sprites/hero/body/robe_white_green.png",
  "./sprites/hero/body/scalemail.png",
  "./sprites/hero/body/shirt_white1.png",
  "./sprites/hero/hand1/axe_executioner.png",
  "./sprites/hero/hand1/blessed_blade.png",
  "./sprites/hero/hand1/broadsword.png",
  "./sprites/hero/hand1/dagger.png",
  "./sprites/hero/hand1/double_sword.png",
  "./sprites/hero/hand1/falchion.png",
  "./sprites/hero/hand1/great_mace.png",
  "./sprites/hero/hand1/great_sword.png",
  "./sprites/hero/hand1/great_sword2.png",
  "./sprites/hero/hand1/great_sword3.png",
  "./sprites/hero/hand1/hand_axe.png",
  "./sprites/hero/hand1/katana_slant.png",
  "./sprites/hero/hand1/long_sword_slant.png",
  "./sprites/hero/hand1/long_sword_slant3.png",
  "./sprites/hero/hand1/quarterstaff.png",
  "./sprites/hero/hand1/rapier.png",
  "./sprites/hero/hand1/scimitar.png",
  "./sprites/hero/hand1/scimitar2.png",
  "./sprites/hero/hand1/scimitar3.png",
  "./sprites/hero/hand1/short_sword.png",
  "./sprites/hero/hand1/staff-artefact1.png",
  "./sprites/hero/hand1/staff-artefact3.png",
  "./sprites/hero/hand1/staff-artefact5.png",
  "./sprites/hero/hand1/staff.png",
  "./sprites/hero/hand1/staff_fancy.png",
  "./sprites/hero/hand1/staff_large.png",
  "./sprites/hero/hand1/staff_mage.png",
  "./sprites/hero/hand1/staff_plain.png",
  "./sprites/hero/hand1/staff_ruby.png",
  "./sprites/hero/hand1/staff_sceptre.png",
  "./sprites/hero/hand1/sword_black.png",
  "./sprites/hero/hand1/triple_sword.png",
  "./sprites/hero/head/fhelm_gray3.png",
  "./sprites/hero/head/fhelm_horn2.png",
  "./sprites/hero/head/full_gold.png",
  "./sprites/hero/head/helm_plume.png",
  "./sprites/hero/head/hood_green.png",
  "./sprites/hero/head/hood_white.png",
  "./sprites/hero/head/horned.png",
  "./sprites/hero/head/iron1.png",
  "./sprites/hero/head/taiso_white.png",
  "./sprites/hero/head/wizard_blackgold.png",
  "./sprites/hero/head/wizard_blue.png",
  "./sprites/hero/head/wizard_purple.png",
  "./sprites/item/amulet/bronze.png",
  "./sprites/item/amulet/diamond.png",
  "./sprites/item/amulet/emerald.png",
  "./sprites/item/amulet/garnet.png",
  "./sprites/item/amulet/golden.png",
  "./sprites/item/amulet/jade.png",
  "./sprites/item/amulet/pearl.png",
  "./sprites/item/amulet/ruby.png",
  "./sprites/item/amulet/sapphire.png",
  "./sprites/item/armour/chain_mail1.png",
  "./sprites/item/armour/chain_mail2.png",
  "./sprites/item/armour/crystal_plate.png",
  "./sprites/item/armour/fire_dragon_armour.png",
  "./sprites/item/armour/glove1.png",
  "./sprites/item/armour/glove2.png",
  "./sprites/item/armour/glove3.png",
  "./sprites/item/armour/glove4.png",
  "./sprites/item/armour/glove5.png",
  "./sprites/item/armour/headgear/helmet1.png",
  "./sprites/item/armour/headgear/helmet2.png",
  "./sprites/item/armour/headgear/helmet3.png",
  "./sprites/item/armour/headgear/helmet4.png",
  "./sprites/item/armour/headgear/helmet5.png",
  "./sprites/item/armour/headgear/helmet_ego1.png",
  "./sprites/item/armour/headgear/helmet_ego2.png",
  "./sprites/item/armour/headgear/helmet_ego4.png",
  "./sprites/item/armour/ice_dragon_armour.png",
  "./sprites/item/armour/leather_armour1.png",
  "./sprites/item/armour/leather_armour2.png",
  "./sprites/item/armour/pearl_dragon_armour.png",
  "./sprites/item/armour/plate2.png",
  "./sprites/item/armour/plate3.png",
  "./sprites/item/armour/ring_mail1.png",
  "./sprites/item/armour/robe1.png",
  "./sprites/item/armour/robe2.png",
  "./sprites/item/armour/robe_ego1.png",
  "./sprites/item/armour/robe_ego2.png",
  "./sprites/item/armour/scale_mail1.png",
  "./sprites/item/armour/swamp_dragon_armour.png",
  "./sprites/item/book/dark_blue.png",
  "./sprites/item/book/dark_brown.png",
  "./sprites/item/book/dark_green.png",
  "./sprites/item/book/gold.png",
  "./sprites/item/book/leather.png",
  "./sprites/item/book/magenta.png",
  "./sprites/item/book/metal_blue.png",
  "./sprites/item/book/red.png",
  "./sprites/item/book/silver.png",
  "./sprites/item/gold/01.png",
  "./sprites/item/gold/05.png",
  "./sprites/item/potion/brilliant_blue.png",
  "./sprites/item/potion/golden.png",
  "./sprites/item/potion/magenta.png",
  "./sprites/item/potion/orange.png",
  "./sprites/item/potion/purple_red.png",
  "./sprites/item/potion/ruby.png",
  "./sprites/item/potion/silver.png",
  "./sprites/item/potion/sky_blue.png",
  "./sprites/item/potion/white.png",
  "./sprites/item/potion/yellow.png",
  "./sprites/item/ring/bronze.png",
  "./sprites/item/ring/copper.png",
  "./sprites/item/ring/gold.png",
  "./sprites/item/ring/gold_blue.png",
  "./sprites/item/ring/gold_green.png",
  "./sprites/item/ring/gold_red.png",
  "./sprites/item/ring/granite.png",
  "./sprites/item/ring/i-positive-energy.png",
  "./sprites/item/ring/i-protection.png",
  "./sprites/item/ring/i-teleport.png",
  "./sprites/item/ring/moonstone.png",
  "./sprites/item/ring/opal.png",
  "./sprites/item/ring/plain_black.png",
  "./sprites/item/ring/silver.png",
  "./sprites/item/scroll/scroll-blue.png",
  "./sprites/item/scroll/scroll-green.png",
  "./sprites/item/scroll/scroll-purple.png",
  "./sprites/item/scroll/scroll-red.png",
  "./sprites/item/scroll/scroll-yellow.png",
  "./sprites/item/weapon/blessed_blade.png",
  "./sprites/item/weapon/club.png",
  "./sprites/item/weapon/dagger.png",
  "./sprites/item/weapon/demon_blade.png",
  "./sprites/item/weapon/double_sword.png",
  "./sprites/item/weapon/eveningstar2.png",
  "./sprites/item/weapon/executioner_axe1.png",
  "./sprites/item/weapon/falchion1.png",
  "./sprites/item/weapon/greatsword2.png",
  "./sprites/item/weapon/greatsword3.png",
  "./sprites/item/weapon/hand_axe1.png",
  "./sprites/item/weapon/long_sword1.png",
  "./sprites/item/weapon/long_sword2.png",
  "./sprites/item/weapon/long_sword3.png",
  "./sprites/item/weapon/quarterstaff.png",
  "./sprites/item/weapon/quarterstaff3.png",
  "./sprites/item/weapon/rapier1.png",
  "./sprites/item/weapon/scimitar1.png",
  "./sprites/item/weapon/scimitar2.png",
  "./sprites/item/weapon/scimitar3.png",
  "./sprites/item/weapon/short_sword1.png",
  "./sprites/item/weapon/short_sword2.png",
  "./sprites/item/weapon/spear1.png",
  "./sprites/item/weapon/spear3.png",
  "./sprites/item/weapon/triple_sword.png",
  "./sprites/mon/an_hei_zhan_shi.png",
  "./sprites/mon/an_zhi_chu_long_shen.png",
  "./sprites/mon/an_zhi_hong_mo_jiao_zhu.png",
  "./sprites/mon/an_zhi_huang_quan_jiao_zhu.png",
  "./sprites/mon/an_zhi_ku_lou_jing_ling.png",
  "./sprites/mon/an_zhi_niu_mo_wang.png",
  "./sprites/mon/an_zhi_shuang_tou_jin_gang.png",
  "./sprites/mon/an_zhi_shuang_tou_xue_mo.png",
  "./sprites/mon/an_zhi_wo_ma_jiao_zhu.png",
  "./sprites/mon/ban_shou_tong_ling.png",
  "./sprites/mon/bao_ya_zhi_zhu.png",
  "./sprites/mon/bat.png",
  "./sprites/mon/bian_fu.png",
  "./sprites/mon/blood_giant.png",
  "./sprites/mon/blood_zombie.png",
  "./sprites/mon/boar_black.png",
  "./sprites/mon/boar_white.png",
  "./sprites/mon/bull_general.png",
  "./sprites/mon/bull_guard.png",
  "./sprites/mon/bull_head.png",
  "./sprites/mon/bull_king.png",
  "./sprites/mon/bull_priest.png",
  "./sprites/mon/cat_hook.png",
  "./sprites/mon/cat_rake.png",
  "./sprites/mon/chicken.png",
  "./sprites/mon/chu_long_shen.png",
  "./sprites/mon/da_lao_shu.png",
  "./sprites/mon/deer.png",
  "./sprites/mon/ding_pa_mao_wang.png",
  "./sprites/mon/dragon_archer.png",
  "./sprites/mon/dragon_blade.png",
  "./sprites/mon/dragon_breaker.png",
  "./sprites/mon/dragon_brute.png",
  "./sprites/mon/dragon_general.png",
  "./sprites/mon/dragon_lord.png",
  "./sprites/mon/duo_gou_mao_wang.png",
  "./sprites/mon/duo_jiao_chong.png",
  "./sprites/mon/e_ling_jiang_shi.png",
  "./sprites/mon/e_ling_shi_wang.png",
  "./sprites/mon/fen_chong.png",
  "./sprites/mon/feng_mo_bai_ye_zhu.png",
  "./sprites/mon/feng_mo_diao_xiang.png",
  "./sprites/mon/feng_mo_gong_jian_shou.png",
  "./sprites/mon/feng_mo_hu_wei.png",
  "./sprites/mon/feng_mo_shi_wang.png",
  "./sprites/mon/feng_mo_xie_e_du_she.png",
  "./sprites/mon/feng_mo_xie_e_qian_chong.png",
  "./sprites/mon/gang_ya_zhi_zhu.png",
  "./sprites/mon/hei_e_zhi_zhu.png",
  "./sprites/mon/hong_mo_jiao_zhu.png",
  "./sprites/mon/hong_mo_xie_wei.png",
  "./sprites/mon/hong_mo_zhu_wei.png",
  "./sprites/mon/hong_she.png",
  "./sprites/mon/hong_ye_zhu.png",
  "./sprites/mon/hu_she.png",
  "./sprites/mon/hu_wei.png",
  "./sprites/mon/hua_wen_zhi_zhu.png",
  "./sprites/mon/huan_ying_zhi_zhu.png",
  "./sprites/mon/huang_quan_jiao_zhu.png",
  "./sprites/mon/huo_yan_wo_ma.png",
  "./sprites/mon/jiao_ying.png",
  "./sprites/mon/ju_du_zhi_zhu.png",
  "./sprites/mon/ju_xing_duo_jiao_chong.png",
  "./sprites/mon/ju_xing_ru_chong.png",
  "./sprites/mon/ku_lou_chang_qiang_bing.png",
  "./sprites/mon/ku_lou_chui_bing.png",
  "./sprites/mon/ku_lou_dao_fu_shou.png",
  "./sprites/mon/ku_lou_gong_jian_shou.png",
  "./sprites/mon/kui_jia_chong.png",
  "./sprites/mon/lang.png",
  "./sprites/mon/maggot.png",
  "./sprites/mon/mo_long_ju_e.png",
  "./sprites/mon/moon_spider.png",
  "./sprites/mon/moth.png",
  "./sprites/mon/niu_mo_dou_shi.png",
  "./sprites/mon/niu_mo_fa_shi.png",
  "./sprites/mon/niu_mo_zhan_shi.png",
  "./sprites/mon/orc.png",
  "./sprites/mon/orc_hero.png",
  "./sprites/mon/orc_warrior.png",
  "./sprites/mon/qian_chong.png",
  "./sprites/mon/qian_nian_shu_yao.png",
  "./sprites/mon/rabbit_guard.png",
  "./sprites/mon/rabbit_lord.png",
  "./sprites/mon/rabbit_spider.png",
  "./sprites/mon/rabbit_warrior.png",
  "./sprites/mon/red_moon_demon.png",
  "./sprites/mon/scarecrow.png",
  "./sprites/mon/seal_attendant.png",
  "./sprites/mon/seal_general.png",
  "./sprites/mon/seal_guard.png",
  "./sprites/mon/seal_lord.png",
  "./sprites/mon/sha_chong.png",
  "./sprites/mon/shi_mu_shi_wang.png",
  "./sprites/mon/shi_ren_hua.png",
  "./sprites/mon/shuang_tou_jin_gang.png",
  "./sprites/mon/shuang_tou_xue_mo.png",
  "./sprites/mon/skel_axe.png",
  "./sprites/mon/skel_elite.png",
  "./sprites/mon/skel_general.png",
  "./sprites/mon/skel_warrior.png",
  "./sprites/mon/skeleton.png",
  "./sprites/mon/snowman.png",
  "./sprites/mon/spider.png",
  "./sprites/mon/thunder_general.png",
  "./sprites/mon/thunder_king.png",
  "./sprites/mon/thunder_skel.png",
  "./sprites/mon/thunder_spider.png",
  "./sprites/mon/tian_lang_zhi_zhu.png",
  "./sprites/mon/tiao_tiao_feng.png",
  "./sprites/mon/toad.png",
  "./sprites/mon/wei_si_er_xiao_chong.png",
  "./sprites/mon/wo_ma_zhan_jiang.png",
  "./sprites/mon/woma_guard.png",
  "./sprites/mon/woma_hero.png",
  "./sprites/mon/woma_lord.png",
  "./sprites/mon/woma_warrior.png",
  "./sprites/mon/worm_black.png",
  "./sprites/mon/wu_gong.png",
  "./sprites/mon/xie_e_du_she.png",
  "./sprites/mon/xie_e_qian_chong.png",
  "./sprites/mon/xie_she.png",
  "./sprites/mon/xie_zi.png",
  "./sprites/mon/xue_ren_wang.png",
  "./sprites/mon/yang.png",
  "./sprites/mon/ying_wei.png",
  "./sprites/mon/zombie.png",
  "./sprites/mon/zombie_king.png",
  "./sprites/mon/zuma_archer.png",
  "./sprites/mon/zuma_guard.png",
  "./sprites/mon/zuma_lord.png",
  "./sprites/mon/zuma_statue.png"
]

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches
      .open(CACHE)
      .then((c) => c.addAll(ASSETS))
      .then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

async function page(req) {
  const cache = await caches.open(CACHE)
  const network = fetch(req).then((res) => {
    if (res.ok) cache.put('./index.html', res.clone())
    return res
  })
  network.catch(() => {})
  const slow = new Promise((r) => setTimeout(r, 3000)).then(() => cache.match('./index.html'))
  try {
    return (await Promise.race([network, slow])) || (await network)
  } catch {
    return (await cache.match('./index.html')) || Response.error()
  }
}

async function asset(req) {
  const hit = await caches.match(req)
  if (hit) return hit
  const res = await fetch(req)
  if (res.ok) (await caches.open(CACHE)).put(req, res.clone())
  return res
}

self.addEventListener('fetch', (e) => {
  const req = e.request
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return
  e.respondWith(req.mode === 'navigate' ? page(req) : asset(req))
})
